# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SECRET_BUCKET: ${{ secrets.SECRET_BUCKET }}
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coscmd
    - name: Setup config
      run: |
        coscmd config -a "$SECRET_ID" -s SECRET_KEY -b SECRET_BUCKET -e cos.accelerate.myqcloud.com
    - name: Upload
      run: |
        coscmd upload Minecraft-Mod-Language-Package.zip Minecraft-Mod-Language-Package.zip
